### ISSUE TITLE
Text added to identity number column

### ISSUE THREAD

**Issue by resha007** [moe-lk/sis-php#268]
mistakenly uploaded a bulk template with "no special need" in identity number column and it updated in the system.

**Comment by gprasangika** [comment]
Bug is fixed with PR #511 and #514 to master of bulk-upload repo. Ready to deploy.

**Comment by resha007** [comment]
after this, the Identity number becomes required. getting error for not adding identity type and identity number.


[1602224355_06366_Grade-10-A_1551261343_student_bulk_data (1).xlsx](https://github.com/moe-lk/sis-php/files/5352917/1602224355_06366_Grade-10-A_1551261343_student_bulk_data.1.xlsx)
[1602224355_06366_Grade-10-A_1551261343_student_bulk_data (2).xlsx](https://github.com/moe-lk/sis-php/files/5352918/1602224355_06366_Grade-10-A_1551261343_student_bulk_data.2.xlsx)

**Comment by mohamednizar** [comment]
@gprasangika  
change the validation rules from 
` '*.identity_type' => 'required_with:identity_number',
 '*.identity_number' => 'required_with:identity_type|regex:/^[0-9]+$/|min:4|max:12',`
to 
` '*.identity_type' => 'required_with:*.identity_number',
 '*.identity_number' => 'required_with:*.identity_type|regex:/^[0-9]+$/|min:4|max:12',`

**Comment by gprasangika** [comment]
The issue will be fixed with PR #524 and #527 to UAT. Following changes need to be done with insert and update sheets in order to avoid conflicts.

- [ ] Remove **NIC type** from Student's **Identity Type column** in **Insert sheet**

- [ ] Remove Student's **Identity type column** from **Update sheet**

Identity type validation in StudentUpdate.php can be removed after the above mentioned change to update sheet. This will be done in a future PR.

**Comment by gprasangika** [comment]
Issue will be fixed with PRs #567, #569 and #570 to UAT. Test passed in Local. Will be deployed after testing in UAT.

**Comment by gprasangika** [comment]
Issue will be fixed with PRs #567, #569 and #570 to UAT branch in bulk-upload repository. Test passed in Local. Will be deployed after testing in UAT.
